--删除用户
drop  user Employee CASCADE;

--创建用户并赋予DBA权限
create user employee IDENTIFIED by 12345;
grant CONNECT,RESOURCE to employee;

--收回权限
revoke CONNECT,RESOURCE from employee;


--插入数据

--补发补扣信息表

--单位变动信息表

--用户表
INSERT INTO "EMPLOYEE"."TB_USER" (ID, PASSWORD, USERTYPE) VALUES ('201320', '6F61D705F46187274ABD65D2FF3EA0EA', '1');
INSERT INTO "EMPLOYEE"."TB_USER" (ID, PASSWORD, USERTYPE) VALUES ('201323', '9F666CDC445BCBF60A6B4DD895F2545B', '0');
INSERT INTO "EMPLOYEE"."TB_USER" (ID, PASSWORD, USERTYPE) VALUES ('201311', '62692F6D94F3792D7AB8C1403F9DE7FE', '0');
INSERT INTO "EMPLOYEE"."TB_USER" (ID, PASSWORD, USERTYPE) VALUES ('201333', '13E88AA34C30BDC50B086CC4CE79A568', '0');

--职工信息表

--专业技术人员岗位工资表             																			主键---级数---岗位---工资标准---起点薪级
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('1', '1', '正高级', '2800', '39');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('2', '2', '正高级', '1900', '25');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('3', '3', '正高级', '1630', '25');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('4', '4', '正高级', '1420', '25');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('5', '5', '副高级', '1180', '16');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('6', '6', '副高级', '1040', '16');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('7', '7', '副高级', '930', '16');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('8', '8', '中级', '780', '9');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('9', '9', '中级', '730', '9');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('10', '10', '中级', '680', '9');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('11', '11', '初级', '620', '5');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('12', '12', '初级', '590', '5');
INSERT INTO "EMPLOYEE"."PROFPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('13', '13', '员级', '550', '1');

--专业技术人员薪级工资标准表														主键---薪级---工资标准
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('1', '1', '80');    
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('2', '2', '91');    
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('3', '3', '102');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('4', '4', '113');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('5', '5', '125');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('6', '6', '137');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('7', '7', '151');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('8', '8', '165');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('9', '9', '181');   
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('10', '10', '197'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('11', '11', '215'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('12', '12', '233'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('13', '13', '253'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('14', '14', '273'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('15', '15', '295'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('16', '16', '317'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('17', '17', '341'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('18', '18', '365'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('19', '19', '391'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('20', '20', '417'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('21', '21', '443'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('22', '22', '471'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('23', '23', '499'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('24', '24', '527'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('25', '25', '555'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('26', '26', '583'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('27', '27', '613'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('28', '28', '643'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('29', '29', '673'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('30', '30', '703'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('31', '31', '735'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('32', '32', '767'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('33', '33', '799'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('34', '34', '834'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('35', '35', '869'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('36', '36', '904'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('37', '37', '944'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('38', '38', '984'); 
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('39', '39', '1024');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('40', '40', '1064');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('41', '41', '1109');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('42', '42', '1154');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('43', '43', '1199');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('44', '44', '1244');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('45', '45', '1289');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('46', '46', '1334');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('47', '47', '1384');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('48', '48', '1434');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('49', '49', '1484');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('50', '50', '1534');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('51', '51', '1590');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('52', '52', '1655');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('53', '53', '1720');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('54', '54', '1785');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('55', '55', '1850');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('56', '56', '1920');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('57', '57', '1990');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('58', '58', '2060');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('59', '59', '2130');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('60', '60', '2200');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('61', '61', '2280');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('62', '62', '2360');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('63', '63', '2440');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('64', '64', '2520');
INSERT INTO "EMPLOYEE"."PROFPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('65', '65', '2600');

--专业技术人员薪级工资套改表																																	主键---套改年限下界---任职年限下界---薪级---岗位级别---套改年限上界---任职年限上界
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('1', '25', '0', '39', '1', '50', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('2', '25', '0', '25', '2', '50', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('3', '25', '0', '25', '3', '50', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('4', '25', '0', '25', '4', '50', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('5', '16', '0', '16', '5', '41', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('6', '16', '0', '16', '6', '41', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('7', '16', '0', '16', '7', '41', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('8', '9', '0', '9', '8', '37', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('9', '9', '0', '9', '9', '37', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('10', '9', '0', '9', '10', '37', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('11', '5', '0', '5', '11', '33', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('12', '5', '0', '5', '12', '33', '45');
INSERT INTO "EMPLOYEE"."PROFSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('13', '1', '0', '1', '13', '30', '45');

--管理人员岗位工资表																主键---薪级---工资标准
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('1', '1', '80');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('2', '2', '91');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('3', '3', '102');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('4', '4', '113');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('5', '5', '125');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('6', '6', '137');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('7', '7', '151');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('8', '8', '165');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('9', '9', '181');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('10', '10', '197');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('11', '11', '215');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('12', '12', '233');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('13', '13', '253');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('14', '14', '273');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('15', '15', '295');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('16', '16', '317');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('17', '17', '341');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('18', '18', '365');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('19', '19', '391');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('20', '20', '417');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('21', '21', '443');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('22', '22', '471');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('23', '23', '499');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('24', '24', '527');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('25', '25', '555');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('26', '26', '583');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('27', '27', '613');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('28', '28', '643');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('29', '29', '673');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('30', '30', '703');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('31', '31', '735');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('32', '32', '767');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('33', '33', '799');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('34', '34', '834');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('35', '35', '869');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('36', '36', '904');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('37', '37', '944');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('38', '38', '984');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('39', '39', '1024');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('40', '40', '1064');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('41', '41', '1109');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('42', '42', '1154');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('43', '43', '1199');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('44', '44', '1244');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('45', '45', '1289');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('46', '46', '1334');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('47', '47', '1384');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('48', '48', '1434');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('49', '49', '1484');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('50', '50', '1534');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('51', '51', '1590');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('52', '52', '1655');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('53', '53', '1720');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('54', '54', '1785');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('55', '55', '1850');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('56', '56', '1920');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('57', '57', '1990');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('58', '58', '2060');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('59', '59', '2130');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('60', '60', '2200');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('61', '61', '2280');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('62', '62', '2360');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('63', '63', '2440');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('64', '64', '2520');
INSERT INTO "EMPLOYEE"."MANPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('65', '65', '2600');

--管理人员薪级工资标准表        																			主键---级数---岗位---工资标准---起点薪级
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('1', '1', '正省', '2750', '46');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('2', '2', '副省', '2130', '39');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('3', '3', '正厅', '1640', '31');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('4', '4', '副厅', '1305', '26');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('5', '5', '正处', '1045', '21');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('6', '6', '副处', '850', '17');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('7', '7', '正科', '720', '12');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('8', '8', '副科', '640', '8');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('9', '9', '科员', '590', '4');
INSERT INTO "EMPLOYEE"."MANPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('10', '10', '员级', '550', '1');
--管理人员薪级工资套改表																																	主键---套改年限下界---任职年限下界---薪级---岗位级别---套改年限上界---任职年限上界
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('1', '46', '0', '46', '1', '60', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('2', '39', '0', '39', '2', '56', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('3', '31', '0', '31', '3', '49', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('4', '26', '0', '26', '4', '46', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('5', '21', '0', '21', '5', '43', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('6', '17', '0', '17', '6', '40', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('7', '12', '0', '12', '7', '37', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('8', '8', '0', '8', '8', '34', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('9', '4', '0', '4', '9', '31', '45');
INSERT INTO "EMPLOYEE"."MANSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('10', '1', '0', '1', '10', '30', '45');


--工人岗位工资表																						主键---级数---岗位---工资标准---起点薪级
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('1', '1', '技术工一级', '830', '26');
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('2', '2', '技术工二级', '690', '20');
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('3', '3', '技术工三级', '615', '14');
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('4', '4', '技术工四级', '575', '8');
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('5', '5', '技术工五级', '545', '2');
INSERT INTO "EMPLOYEE"."WORPOSISAL_TABLE" (ID, STAGE, POSITION, SALARYSTANDARD, STARTPAYLEVEL) VALUES ('6', '6', '普通工', '540', '1');

--工人薪级工资标准表																主键---薪级---工资标准
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('1', '1', '70');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('2', '2', '80');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('3', '3', '90');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('4', '4', '101');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('5', '5', '112');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('6', '6', '124');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('7', '7', '136');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('8', '8', '148');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('9', '9', '161');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('10', '10', '174');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('11', '11', '188');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('12', '12', '202');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('13', '13', '217');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('14', '14', '232');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('15', '15', '248');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('16', '16', '264');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('17', '17', '282');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('18', '18', '300');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('19', '19', '320');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('21', '21', '340');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('22', '22', '386');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('23', '23', '409');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('24', '24', '432');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('25', '25', '455');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('26', '26', '478');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('27', '27', '504');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('28', '28', '530');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('29', '29', '556');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('30', '30', '585');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('31', '31', '614');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('32', '32', '643');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('33', '33', '675');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('34', '34', '707');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('35', '35', '739');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('36', '36', '774');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('37', '37', '809');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('38', '38', '844');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('39', '39', '879');
INSERT INTO "EMPLOYEE"."WORPAYLSAL_TABLE" (ID, PAYLEVEL, SALARYSTANDARD) VALUES ('40', '40', '915');

--工人薪级工资套改表																																	主键---套改年限下界---任职年限下界---薪级---岗位级别---套改年限上界---任职年限上界
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('1', '26', '0', '26', '1', '38', '45');
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('2', '20', '0', '20', '2', '36', '45');
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('3', '14', '0', '14', '3', '33', '45');
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('4', '8', '0', '8', '4', '30', '45');
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('5', '2', '0', '2', '5', '28', '45');
INSERT INTO "EMPLOYEE"."WORSALCHA_TABLE" (ID, LOWBOUNDOFCHANGEYEAR, LOWBOUNDOFOFFICEYEAR, PAYLEVEL, POSITIONLEVEL, UPPERBOUNDOFCHANGEYEAR, UPPERBOUNDOFOFFICEYEAR) VALUES ('6', '1', '0', '1', '6', '25', '45');

--薪水表
